export enum AppEvents {
    SET_MAX_VALUE = 'COUNTER/SET_MAX_VALUE',
    SET_MIN_VALUE = 'COUNTER/SET_MIN_VALUE',
    SET_CURRENT_VALUE = 'COUNTER/SET_CURRENT_VALUE',
    SET_ERROR = 'COUNTER/SET_ERROR',
    SET_EDIT_MODE = 'SET_EDIT_MODE',
    SET_VALUES_FROM_LC = 'COUNTER/SET_VALUES_FROM_LC'
}